# Generated by Django 4.2 on 2025-06-15 17:08

from django.db import migrations, models
import django.utils.timezone
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('symptoms', models.TextField()),
                ('priority', models.CharField(choices=[('kritis', 'Kritis'), ('mendesak', 'Mendesak'), ('biasa', 'Biasa')], default='biasa', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('adjusted_priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
            ],
        ),
    ]
